name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust based on your Laravel version

      # Step 3: Install composer dependencies
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 4: Cache Laravel configuration and routes
      - name: Cache Configuration and Routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Step 5: Install Node.js and build assets
      - name: Install Node.js and Build Assets
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci && npm run build

      # Step 6: Deploy to cPanel via SSH
      - name: Deploy to cPanel
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          REMOTE_PORT: ${{ secrets.CPANEL_SSH_PORT }}
          TARGET: ${{ secrets.CPANEL_TARGET }}

      # Step 7: Run Laravel-specific setup commands
      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          port: ${{ secrets.CPANEL_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.CPANEL_TARGET }}
            php artisan key:generate
            php artisan migrate --force
            php artisan optimize
